import AOS from 'aos';
import "../js/parallaxContainer";
import "../js/parallaxImages";
import "../js/parllexEffect";
import "../js/navBar";
import "../js/swiper";
import "../js/towns";
import "../js/imgChanger";
import "../js/typeStyle";
import "../js/footer";
AOS.init();
